version: 2.1

var_1: &cache_key v1-monorepo-16.8.0-{{ checksum "package-lock.json" }}
var_2: &workspace_location .
commands:
  fail_fast:
    steps:
      - run:
          name: 'Cancel workflow on fail'
          when: on_fail
          command: echo "Cancel job"

  attach_workspace_default:
    description: Attach workspace at a predefined location
    steps:
      - attach_workspace:
          at: *workspace_location

jobs:
  setup:
    docker:
      - image: cimg/node:16.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - *cache_key
      - run: npm i
      - persist_to_workspace:
          root: *workspace_location
          paths:
            - ./*
      - save_cache:
          key: *cache_key
          paths:
            - ~/.cache/npm

  build:
    docker:
      - image: cimg/node:16.8.0
    steps:
      - attach_workspace_default
      - run: npm run build

  test:
    docker:
      - image: cimg/node:16.8.0
    steps:
      - run: echo "tests pass"
      - fail_fast

  lint:
    docker:
      - image: cimg/node:16.8.0
    steps:
      - attach_workspace_default
      - run: npm run lint

  deploy:
    docker:
      - image: cimg/node:16.8.0
    steps:
      - attach_workspace_default
      - run: echo "placeholder for deploy"
      - run:
          name: 'Update package.json, package-lock.json'
          command: bash ci/test-before.sh
      - run:
          name: 'Create release folder'
          command: bash ci/build-server.sh
      - run:
          name: 'Deploy to AWS'
          command: echo "Deploying to aws..."

workflows:
  version: 2
  default_workflow:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - build:
          requires:
            - setup
      - test:
          requires:
            - build
      - deploy:
          requires:
            - lint
            - build
            - test
