version: 2.1

var_1: &cache_key v1-monorepo-{{ checksum "package-lock.json" }}
var_2: &workspace_location .

executors:
  node-executor:
    docker:
      - image: cimg/node:latest

commands:
  fail_fast:
    steps:
      - run:
          name: 'Cancel workflow on fail'
          when: on_fail
          command: curl -X POST "https://circleci.com/api/v2/workflow/$CIRCLE_WORKFLOW_ID/cancel?circle-token=$CIRCLE_API_TOKEN"

  attach_workspace_default:
    description: Attach workspace at a predefined location
    steps:
      - attach_workspace:
          at: *workspace_location

jobs:
  setup:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - *cache_key
      - run: npm i
      - persist_to_workspace:
          root: *workspace_location
          paths:
            - ./*
      - save_cache:
          key: *cache_key
          paths:
            - node_modules
            - ./apps/**/node_modules
            - ./packages/**/node_modules

  build:
    executor: node-executor
    steps:
      - attach_workspace_default
      - run: npm run build
      - persist_to_workspace:
          root: *workspace_location
          paths:
            - ./*
      - fail_fast

  test:
    executor: node-executor
    steps:
      - run: echo "tests pass"
      - fail_fast

  lint:
    executor: node-executor
    steps:
      - attach_workspace_default
      - run: npm run lint
      - fail_fast

  release:
    executor: node-executor
    steps:
      - attach_workspace_default
      - run:
          name: 'Update package.json, package-lock.json'
          command: bash ci/test-before.sh
      - run:
          name: 'Create release folder'
          command: bash ci/build-server.sh
      - persist_to_workspace:
            root: .
            paths:
              - release
      - fail_fast

  deploy:
    executor: node-executor
    steps:
      - attach_workspace_default
      - run:
          name: 'Deploy to AWS'
          command: echo "Deploying to aws..."

workflows:
  version: 2
  default_workflow:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - build:
          requires:
            - setup
      - test:
          requires:
            - build
      - release:
          requires:
            - lint
            - build
            - test
      - deploy:
          requires:
            - release
