version: 2.1

commands:
  fail_fast:
    steps:
      - run:
          name: 'Cancel workflow on fail'
          when: on_fail
          command: echo "Cancel job"

jobs:
  setup:
    docker:
      - image: cimg/node:16.8.0
    steps:
      - checkout
      - run: npm i
      - fail_fast

  build:
    docker:
      - image: cimg/node:16.8.0
    steps:
      - run: npm run build
      - fail_fast

  test:
    docker:
      - image: cimg/node:16.8.0
    steps:
      - run: echo "tests pass"
      - fail_fast

  lint:
    docker:
      - image: cimg/node:16.8.0
    steps:
      - run: npm run lint
      - fail_fast

  deploy:
    docker:
      - image: cimg/node:16.8.0
    steps:
      - run: echo "placeholder for deploy"
      - run:
          name: 'Update package.json, package-lock.json'
          command: bash ci/test-before.sh
      - run:
          name: 'Create release folder'
          command: bash ci/build-server.sh
      - run:
          name: 'Deploy to AWS'
          command: echo "Deploying to aws..."

workflows:
  version: 2
  default_workflow:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - build:
          requires:
            - setup
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
            - test
